package com.hospital.smartqueue.doctor.scheduling.application;
import com.hospital.smartqueue.common.domain.*; import com.hospital.smartqueue.common.infrastructure.AuditService; import com.hospital.smartqueue.doctor.scheduling.api.*; import com.hospital.smartqueue.doctor.scheduling.domain.ScheduleException; import com.hospital.smartqueue.doctor.scheduling.infrastructure.ScheduleExceptionRepository; import org.junit.jupiter.api.*; import java.time.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class ScheduleExceptionServiceTest { SchedulingAccessContext access=mock(SchedulingAccessContext.class); ScheduleExceptionRepository repo=mock(ScheduleExceptionRepository.class); AuditService audit=mock(AuditService.class); ScheduleExceptionService service=new ScheduleExceptionService(access,repo,audit); UUID h=UUID.randomUUID(),b=UUID.randomUUID(),d=UUID.randomUUID(),id=UUID.randomUUID();
 @Test void createsException(){var r=new ScheduleExceptionRequest(LocalDate.of(2026,1,2),null);when(repo.existsByDoctorIdAndBranchIdAndExceptionDate(d,b,r.date())).thenReturn(false);when(repo.save(any())).thenAnswer(x->x.getArgument(0));assertEquals(r.date(),service.create(h,b,d,r).getExceptionDate());verify(access).requireManage(h,b,d);verify(repo).save(any());}
 @Test void readsAndUpdatesOwnedException(){var e=new ScheduleException(d,b,LocalDate.of(2026,1,2));when(repo.findByIdAndDoctorIdAndBranchId(id,d,b)).thenReturn(Optional.of(e));assertSame(e,service.get(h,b,d,id));assertEquals(LocalDate.of(2026,1,3),service.update(h,b,d,id,new ScheduleExceptionRequest(LocalDate.of(2026,1,3),0L)).getExceptionDate());verify(access).requireRead(h,b,d);}
 @Test void deletesWithCurrentVersion(){var e=new ScheduleException(d,b,LocalDate.now());when(repo.findByIdAndDoctorIdAndBranchId(id,d,b)).thenReturn(Optional.of(e));service.delete(h,b,d,id,0);verify(repo).delete(e);}
 @Test void rejectsDuplicateAndStaleUpdate(){var r=new ScheduleExceptionRequest(LocalDate.now(),null);when(repo.existsByDoctorIdAndBranchIdAndExceptionDate(d,b,r.date())).thenReturn(true);assertThrows(ConflictException.class,()->service.create(h,b,d,r));var e=new ScheduleException(d,b,LocalDate.now());when(repo.findByIdAndDoctorIdAndBranchId(id,d,b)).thenReturn(Optional.of(e));assertThrows(ConflictException.class,()->service.update(h,b,d,id,new ScheduleExceptionRequest(LocalDate.now(),null)));}
 @Test void propagatesDeniedAccess(){doThrow(new DomainException("FORBIDDEN","no")).when(access).requireManage(h,b,d);assertThrows(DomainException.class,()->service.create(h,b,d,new ScheduleExceptionRequest(LocalDate.now(),null)));}
}
